#服务端口号
server:
  port: 8002
#服务名
spring:
  application:
    name: service-vod

  servlet:
    multipart:
      enabled: true #是否启用http上传
      max-request-size: 1024MB #最大总上传文件大小
      max-file-size: 1024MB #设置单个文件最大长度
#nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#环境设置
  profiles:
    active: dev
#阿里云 vod
aliyun:
  vod:
    file:
      keyid: LTAI5tRPoQ8YBUDus7F5RsTX
      keysecret: Jg4ZYNvWIJBWskW6ZZ5KXycJcNNZMN