#服务器端口号
server:
  port: 8006

spring:
  application:
    name: service-statistics

  #mysql数据库
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql:///edu?serverTimezone=GMT%2B8
    username: root
    password: 123456
  #返回json数据的全局格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 192.168.200.130
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞时间（复数表示没有限制）
        max-idle: 5
        min-idle: 0


  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis-plus:
  mapper-locations: classpath:com/kenProject/statservice/mapper/xml/*.xml