#端口号
server:
  port: 10000
#服务名
spring:
  application:
    name: canal-client
#环境配置
  profiles:
    active: dev
#mysql数据库连接
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql:///kendb?serverTimezone=GMT%2B8
    username: root
    password: 123456