#服务器端口号
server:
  port: 8001
#服务名
spring:
  application:
    name: service-oss
  #环境设置
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true #是否启用http上传
      max-request-size: 10MB #最大请求文件大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘`写入
  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#阿里云 OOS
aliyun:
  oss:
    file:
      endpoint: oss-cn-beijing.aliyuncs.com
      keyid: LTAI5tRPoQ8YBUDus7F5RsTX
      keysecret: Jg4ZYNvWIJBWskW6ZZ5KXycJcNNZMN
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: education-ken
